services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_sky
    volumes:
      - ./:/var/www/html
    networks:
      - network

  webserver:
    image: nginx:alpine
    container_name: laravel_sky_webserver
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./dockerFiles/nginx/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - app
    networks:
      - network

  db:
    image: mysql:8.0
    container_name: laravel_sky_db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: db-name
      MYSQL_USER: username
      MYSQL_PASSWORD: "password"
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./dockerFiles/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
    command: [
        "mysqld",
        "--init-file=/docker-entrypoint-initdb.d/init.sql"
    ]

volumes:
  dbdata:

networks:
  network:
    driver: bridge
